version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"    
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/frontback
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - database


  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=frontback
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
